import { Header } from '@/components/header'
import './globals.css'
import style from './layout.module.css'


export const metadata = {
  title: 'Home | Eduardo Mendes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={style.body}>
        <Header />
        <main className={style.containerLayout}>
          {children}
        </main>
      </body>
    </html>
  )
}
